basePath: /
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.Menu:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      isRecommended:
        type: boolean
      itemDescription:
        type: string
      itemName:
        type: string
      itemPriceLarge:
        type: number
      itemPriceMedium:
        type: number
      itemPriceSmall:
        type: number
      itemType:
        type: string
      pictureName:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:3001
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a simple API for Cafka cafe.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Cafka API
  version: "1.0"
paths:
  /api/menu:
    get:
      consumes:
      - application/json
      description: Get all menus
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Menu'
            type: array
      summary: Get all menus
      tags:
      - Menu
    post:
      consumes:
      - application/json
      description: Create a menu
      parameters:
      - description: Menu
        in: body
        name: menu
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: Create a menu
      tags:
      - Menu
swagger: "2.0"
